version: ‘3.7’
services:
   web_sandbox:
      build:
         context: ./Plain-Webserver
         dockerfile: Dockerfile
      ports:
         - 7001:80  
   sonatype_nexus:
      image: sonatype/nexus3
      ports:
         - 8081:8081
   sonarqube:
      image: sonarqube
      ports:
         - 9000:9000
   jenkins:
      build:
         context: ./Jenkins
         dockerfile: Dockerfile
      ports:
         - 8080:8080